### PR TITLE
dsn does not exist in the DB2 credential for Standard instance. It must be built manually per DB2 support team

### PR DESCRIPTION
**Pull request by lee-zhg**

### CODE REVIEW

**Review by data-henrik — CHANGES_REQUESTED** [review]
The code could be simplified by first obtaining the actual connection structure, then using it to extract the parameters. The commented lines for the logging should be removed.

**Comment by data-henrik** [comment]
Instead of addressing all transformation in the app code, I would like to see driver changes. I opened https://github.com/ibmdb/node-ibm_db/issues/719

**Comment by lee-zhg** [comment]
The commented lines for the logging were removed.

Regarding to your comments "The code could be simplified by first obtaining the actual connection structure, then using it to extract the parameters", do you have a sample code? I am not sure what you mean.

**Comment by data-henrik** [comment]
You could so something like:
`const db2ConnectionInfo = params.__bx_creds[Object.keys(params.__bx_creds)[0]].connection.db2`

and then reuse db2ConnectionInfo

`const dbname=db2ConnectionInfo.database`

**Comment by lee-zhg** [comment]
Thank you for the explanation. 

I don't see much difference. What you explained and the current changes are almost identical.

**Pull request merged**
